---
abstract: 'yamlval vmethod for Template Toolkit'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Template::Plugin::YAMLVal
name: Template-Plugin-YAMLVal
no_index:
  directory:
    - inc
    - t
requires:
  Template::Toolkit::Simple: 0.13
  YAML: 0.72
  YAML::XS: 0.35
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
